#################################################
#                     HBans                     #
#               Plugin by: Alison               #
#             © Copyright HubCode's             #
#################################################

#Permissões
#HBans.Ban
#HBans.IpBan
#HBans.Mute
#HBans.tempban
#HBans.tempmute
#HBans.unmute
#HBans.unban
#HBans.ipunban
#HBans.unwarn
#HBans.kick
#HBans.warn
#HBans.reportes
#HBans.verificar
#HBans.Imune."comando"

#Sumário
#%sender = player/staffer que digitou o comando
#%b = player punido
#%m = motivo
#%t = momento em que o tempban do player expira
#%q = quantidade de warns removidas

#Opções de integração
Twitter: false
Discord: false
Twitter-Reportes: false
Discord-Reportes: false

#Detalhes do bot
Bot:
  Token: 'XXX-XXX-XXX-XXX'
  Presence: 'HubCodes.tk'
  Canal: 'XXX-XXX-XXX-XXX'
  Canal-Reportes: 'XXX-XXX-XXX-XXX'

#Opção de MySQL
MySQL:
  Ativado: false
  Host: 'Ip da Host'
  Port: 'Porta da Host'
  User: 'SeuUsuario'
  Database: 'SuaDatabase'
  Pass: 'SuaSenha'

#Login Punido
BanLogin:
  - '    &bHBans'
  - ' '
  - '&cVoce esta permanentemente banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - 'Compre seu unban em: HBans.com.br'
  
IpBanLogin:
  - '    &bHBans'
  - ' '
  - '&cSeu ip esta permanentemente banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - 'Compre seu unban em: HBans.com.br'
  
MuteChat:
  - '    &bHBans'
  - '&c• Voce esta permanentemente Mutado'
  - '&c• Motivo: %m'  
  
Report:
  - '     &bHBans'
  - '&cPlayer Reportado'
  - '&cAguarde até que um staff veja'
  - ''
  
TempBanLogin:
  - '    &bHBans'
  - ' '
  - '&cVoce esta temporariamente banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - '&cExpira em: %t'
  - 'Compre seu unban em: HBans.com.br'
  
TempMuteChat:
  - '    &bHBans'
  - '&c• Voce esta Mutado por %t'
  - '&c• Motivo: %m'

KickLogin:
  - ' &bHBans'
  - ' '
  - '&cVoce foi kickado'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - ' '

#Punições
Ban:
  - '     &bHBans'
  - '&c• &6%sender &cBaniu o Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Duração Da Punição: Permanente'
  
IpBan:
  - '     &bHBans'
  - '&c• &6%sender &cBaniu o ip do Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Duração Da Punição: Permanente'
  
Mute:
  - '     &bHBans'
  - '&c• &6%sender &cMutou o Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Duração Da Punição: Permanente'
  
ReportS:
  - '  &bHBans'
  - '&cNovo Reporte'
  - '&cDigite /reportes para ve-lo'
  - ''
  
TempBan:
  - '     &bHBans'
  - '&c• &6%sender &cBaniu o Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Expira em: %t'
  
TempMute:
  - '     &bHBans'
  - '&c• &6%sender &cMutou o Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Expira em: %t'
  
Kick:
  - '     &bHBans'
  - '&c• &6%sender &cKickou o Jogador &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Duração Da Punição: ERROR 404 :P'
  
Warn:
  - '     &bHBans'
  - '&c• &6%sender &cdeu uma Warn Para &6%b'
  - '&c• Motivo Da Punição: %m'
  - '&c• Duração Da Punição: ERROR 404 :P'

#Twitter
#As mensagens só serão mostradas se a opção
#de integração ao Twitter estiver ligada
BanT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - '• %sender Baniu o Jogador %b'
  - '• Motivo Da Punição: %m'
  - '• Duração Da Punição: Permanente'
  
IpBanT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - '• %sender Baniu o ip do Jogador %b'
  - '• Motivo Da Punição: %m'
  - '• Duração Da Punição: Permanente'
  
TempBanT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - '• %sender Baniu o Jogador %b'
  - '• Motivo Da Punição: %m'
  - '• Expira em: %t'
  
MuteT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - '• %sender Mutou o Jogador %b'
  - '• Motivo Da Punição: %m'
  - '• Duração Da Punição: Permanente'
  
TempMuteT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - '• %sender Mutou o Jogador %b'
  - '• Motivo Da Punição: %m'
  - '• Expira em: %t'
  
ReportT:
  - '-=-=-=-=-=-HBans-=-=-=-=-=-'
  - 'Reportado: %b'
  - 'Reporter: %sender'
  - 'Motivo: %m'
  
#Discord
#As mensagens só serão mostradas se a opção
#de integração ao Discord estiver ligada
BanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '• %sender Baniu o Jogador %b'
    - '• Motivo Da Punição: %m'
    - '• Duração Da Punição: Permanente'
    
IpBanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '• %sender Baniu o ip do Jogador %b'
    - '• Motivo Da Punição: %m'
    - '• Duração Da Punição: Permanente'
  
TempBanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '-=-=-=-=-=-HBans-=-=-=-=-=-'
    - '• %sender Baniu o Jogador %b'
    - '• Motivo Da Punição: %m'
    - '• Expira em: %t'
  
MuteD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '• %sender Mutou o Jogador %b'
    - '• Motivo Da Punição: %m'
    - '• Duração Da Punição: Permanente'

TempMuteD:
  Imagem: true
  Titulo: '**Novo Report**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '-=-=-=-=-=-HBans-=-=-=-=-=-'
    - '• %sender Mutou o Jogador %b'
    - '• Motivo Da Punição: %m'
    - '• Expira em: %t'
  
ReportD:
  Imagem: true
  Titulo: '**Novo Report**'
  Footer: 'HBans'
  ImagemLink: 'https://static.wixstatic.com/media/af3f9b_22ded659dc7d412ea711c23082e6e21e~mv2.gif'
  ImagemFooter: 'https://HubCodes.tk/assets/img/logosz2.png'
  Mensagem:
    - '• Reportado: %b'
    - '• Reporter: %sender'
    - '• Motivo: %m'
  
#Comando Incorreto
BanI: '&cUse: /ban <Player> <Motivo>'
IpBanI: '&cUse: /ipban <Player> <Motivo>'
MuteI: '&cUse: /mute <Player> <Motivo>'
TempBanI: '&cUse: /tempban <Player> <Tempo> <Minutos/Horas/Dias> <Motivo>'
TempMuteI: '&cUse: /tempmute <Player> <Tempo> <Minutos/Horas/Dias> <Motivo>'
UnmuteI: '&cUse: /unmute <Player>'
UnbanI: '&cUse: /unban <Player>'
IpUnbanI: '&cUse: /ipunban <Player/IP>'
UnwarnI: '&cUse: /unwarn <Player> <um/todos>'
KickI: '&cUse: /kick <Player> <Motivo>'
WarnI: '&cUse: /warn <Player> <Motivo>'
ReportarI: '&cUse: /reportar <Player> <Motivo>'
ReportesI: '&cUse: /reportes'
VerificarI: '&cUse: /verificar <Player>'

#Mensagens
Prefix: '&bHBans &6»'
SemPermissao: '&cVocê não tem permissão para usar este comando!'
JaBanido: '&cEste jogador já esta banido!'
JaMute: '&cEste jogador já esta mutado!'
JaUnmute: '&cEste jogador não está mutado!'
JaUnban: '&cEste jogador não está banido!'
Unmute: '&aVocê desmutou o jogador %b'
Unban: '&aVoce desbaniu o jogador %b'
IpUnban: '&aVoce desbaniu o ip do jogador %b'
Unwarn: '&aVocê removeu %q warns de %b'
PlayerOff: '&cEste player não esta conectado ao servidor'
PlayerImune: '&cEste player é imune a essa punição'
FormatoI: '&cNumero invalido ou muito alto'
UnwarnM: '&cEsse player não possui warns'
DenunciaNegada: '&cDenuncia negada com sucesso'
DenunciaAceita: '&aPunição aplicada com sucesso'
DenunciaTeleporte: '&aTeleportado com sucesso'

#Outros
#Comando que será executado caso o player receba 3 warns
ComandoWarn: 'ban %b'
#Comando que será executado quando um report for aceito
ComandoReport: 'ban %b'
#Um som de bigorna alertará um novo reporte aos staffers
SomReport: true