#################################################
#                     HBans                     #
#               Plugin by: Alison               #
#             © Copyright HubCode's             #
#################################################

#Permissões
#hbans.ban
#hbans.ipban
#hbans.mute
#hbans.tempban
#hbans.tempmute
#hbans.unmute
#hbans.unban
#hbans.ipunban
#hbans.unwarn
#hbans.kick
#hbans.warn
#hbans.reportes
#hbans.verificar
#hbans.Imune."comando"

#Sumário
#%sender = player/staffer que digitou o comando;
#%b - player punido;
#%m - motivo;
#%t - momento em que o tempban do player expira;
#%q - quantidade de warns removidas;
#%pb - players banidos até hoje;
#%pm - player mutados até hoje;
#%pr - prova inserida pelo staffer.

#Opções de integração
Twitter: false
Discord: true
Twitter-Reportes: false
Discord-Reportes: true

#Detalhes do bot
Bot:
  Token: ''
  Presence: 'hubcodes.tk'
  Canal: 'id do canal'
  Canal-Reportes: 'id do canal'

MySQL:
  Ativado: false
  Host: ''
  User: ''
  Port: ''
  DataBase: ''
  Password: ''
  
#Configure o "WatchDog"
#Tempo em minutos
WatchDog:
  Ativado: true
  Tempo: '5'
  Mensagem:
    - ''
    - '&6&lPUNIÇÕES APLICADAS'
    - '&8• &fForam banidos &a%pb &fjogadores até o momento'
    - '&8• &fForam mutados &a%pm &fjogadores até o momento'
    - ''

#Configure os motivos de punição
Punir:
  Uso de Hack:
    Comando: 'ban %b %pr (Uso de hack)'
    Permissao: 'hbans.ban'
  Antijogo:
    Comando: 'mute %b %pr (Antijogo)'
    Permissao: 'hbans.mute'  

#Login Punido
BanLogin:
  - '    HBans'
  - ' '
  - '&cVoce esta PERMANENTE banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - 'Compre seu unban em: hubcodes.tk'
  
IpBanLogin:
  - '    HBans'
  - ' '
  - '&cSeu ip esta PERMANENTE banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - 'Compre seu unban em: hubcodes.tk'
  
MuteChat:
  - '    HBans'
  - '&c• Voce esta PERMANENTE Mutado'
  - '&c• Motivo: %m'  
  
Report:
  - '     HBans'
  - '&cPlayer Reportado'
  - '&cAguarde até que um staff veja'
  - ''
  
TempBanLogin:
  - '    HBans'
  - ' '
  - '&cVoce esta temporariamente banido'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - '&cExpira em: %t'
  - 'Compre seu unban em: hubcodes.tk'
  
TempMuteChat:
  - '    HBans'
  - '&c• Voce esta mutado por %t'
  - '&c• Motivo: %m'

KickLogin:
  - ' HBans'
  - ' '
  - '&cVoce foi kickado'
  - '&cMotivo: %m'
  - '&cStaff: %sender'
  - ' '
  - ' '

#Punições
Ban:
  - '     HBans'
  - '&c• &6%sender &cbaniu o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Duração da punição: ETERNO'

BanSilent:
  - '     HBans'
  - '&c• &6%sender &cbaniu o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Duração da punição: ETERNO'
  
IpBan:
  - '     HBans'
  - '&c• &6%sender &cbaniu o IP do jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Duração da punição: ETERNO'
  
Mute:
  - '     HBans'
  - '&c• &6%sender &cmutou o jogador &6%b'
  - '&c• Motivo da dunição: %m'
  - '&c• Duração da punição: ETERNO'

MuteSilent:
  - '     HBans'
  - '&c• &6%sender &cmutou o jogador &6%b'
  - '&c• Motivo da dunição: %m'
  - '&c• Duração da punição: ETERNO'
  
Report:
  - '  HBans'
  - '&cNOVO REPORTE'
  - '&cDigite /reportes para ve-lo'
  - ''
  
TempBan:
  - '     HBans'
  - '&c• &6%sender &cbaniu o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Expira em: %t'

TempBanSilent:
  - '     HBans'
  - '&c• &6%sender &cbaniu o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Expira em: %t'
  
TempMute:
  - '     HBans'
  - '&c• &6%sender &cmutou o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Expira em: %t'

TempMuteSilent:
  - '     HBans'
  - '&c• &6%sender &cmutou o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Expira em: %t'
  
Kick:
  - '     HBans'
  - '&c• &6%sender &ckickou o jogador &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Duração da punição: Nenhum motivo dado'
  
Warn:
  - '     HBans'
  - '&c• &6%sender &cdeu uma warn Para &6%b'
  - '&c• Motivo da punição: %m'
  - '&c• Duração da punição: Nenhum motivo dado'

#Twitter
#As mensagens só serão mostradas se a opção
#de integração ao Twitter estiver ligada
BanT:
  - 'HBans'
  - '• %sender baniu o jogador %b'
  - '• Motivo da punição: %m'
  - '• Duração da punição: ETERNO'
  
IpBanT:
  - 'HBans'
  - '• %sender baniu o ip do jogador %b'
  - '• Motivo da punição: %m'
  - '• Duração da punição: ETERNO'
  
TempBanT:
  - 'HBans'
  - '• %sender baniu o jogador %b'
  - '• Motivo da punição: %m'
  - '• Expira em: %t'
  
MuteT:
  - 'HBans'
  - '• %sender m'
  
TempMuteT:
  - 'HBans'
  - '• %sender m'
  
ReportT:
  - 'HBans'
  - 'Reportado: %b'
  - 'Reporter: %sender'
  - 'Motivo: %m'
  
#Discord
#As mensagens só serão mostradas se a opção
#de integração ao Discord estiver ligada
BanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - '• %sender baniu o jogador %b'
    - '• Motivo da punição: %m'
    - '• Duração da punição: ETERNO'
    
IpBanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - '• %sender baniu o IP do jogador %b'
    - '• Motivo da punição: %m'
    - '• Duração da punição: ETERNO'
  
TempBanD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - 'HBans'
    - '• %sender baniu o jogador %b'
    - '• Motivo da punição: %m'
    - '• Expira em: %t'
  
MuteD:
  Imagem: true
  Titulo: '**Nova Punição**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - '• %sender mutou o jogador %b'
    - '• Motivo da punição: %m'
    - '• Duração da punição: ETERNO'

TempMuteD:
  Imagem: true
  Titulo: '**Novo Report**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - 'HBans'
    - '• %sender mutou o jogador %b'
    - '• Motivo da punição: %m'
    - '• Expira em: %t'
  
ReportD:
  Imagem: true
  Titulo: '**Novo Report**'
  Footer: 'HBans'
  ImagemLink: 'https://i.imgur.com/Hs3POwo.png'
  ImagemFooter: 'https://i.imgur.com/Hs3POwo.png'
  Mensagem:
    - '• Reportado: %b'
    - '• Reporter: %sender'
    - '• Motivo: %m'
  
#Comando Incorreto
PunirI: '&cUse: /punir <player> <prova>'
BanI: '&cUse: /ban <player> <motivo>'
IpBanI: '&cUse: /ipban <player> <motivo>'
MuteI: '&cUse: /mute <player> <motivo>'
TempBanI: '&cUse: /tempban <player> <tempo> <minutos/horas/dias> <motivo>'
TempMuteI: '&cUse: /tempmute <player> <tempo> <minutos/horas/dias> <motivo>'
UnmuteI: '&cUse: /unmute <player>'
UnbanI: '&cUse: /unban <player>'
IpUnbanI: '&cUse: /ipunban <Player/IP>'
UnwarnI: '&cUse: /unwarn <player> <um/todos>'
KickI: '&cUse: /kick <player> <motivo>'
WarnI: '&cUse: /warn <player> <motivo>'
ReportarI: '&cUse: /reportar <player> <motivo>'
ReportesI: '&cUse: /reportes'
VerificarI: '&cUse: /verificar <player>'

#Mensagens
Prefix: '&6REVOLUTION &fMC &6»'
SemPermissao: '&cVocê não tem permissão para usar este comando!'
JaBanido: '&cEste jogador já esta banido!'
JaMute: '&cEste jogador já esta mutado!'
JaUnmute: '&cEste jogador não está mutado!'
JaUnban: '&cEste jogador não está banido!'
Unmute: '&aVocê desmutou o jogador %b'
Unban: '&aVoce desbaniu o jogador %b'
IpUnban: '&aVoce desbaniu o ip do jogador %b'
Unwarn: '&aVocê removeu %q warns de %b'
PlayerOff: '&cEste player não esta conectado ao servidor'
PlayerImune: '&cEste player é imune a essa punição'
FormatoI: '&cNumero invalido ou muito alto'
LinkI: '&cSua prova deve iniciar com http:// ou https://'
UnwarnM: '&cEsse player não possui warns'
DenunciaNegada: '&cDenuncia negada com sucesso'
DenunciaAceita: '&aPunição aplicada com sucesso'
DenunciaTeleporte: '&aTeleportado com sucesso'

#Outros
#Comando que será executado caso o player receba 3 warns
ComandoWarn: 'tempmute %b'
#Comando que será executado quando um report for aceito
ComandoReport: 'ban %b %m'
#Um som de bigorna alertará um novo reporte aos staffers
SomReport: true